[include fluidd.cfg]
[mcu]
serial: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_5543830353935111E061-if00
[virtual_sdcard]
path: /home/printer/printer_data/gcodes
on_error_gcode: CANCEL_PRINT
[printer]
kinematics: cartesian
max_velocity: 30
max_accel: 30
max_z_velocity: 2
max_z_accel: 10
[force_move]
enable_force_move: True
[gcode_macro G28]
rename_existing: G28.1
gcode:
    {% set th = printer.toolhead %}
    {% if th.homed_axes == "" %}
        SET_KINEMATIC_POSITION Z=0
        G0 Z25 F6000
        LOWER_BED
        M84
    {% elif th.position.z < 7 %}
        LOWER_BED
    {% endif %}
    HOME_Y
    HOME_X
    HOME_Z
[gcode_macro HOME_X]
gcode:
    M118 Homing X-Axis...
    G28.1 X0
    G0 X10
[gcode_macro HOME_Y]
gcode:
    M118 Homing Y-Axis...
    G28.1 Y0
    G0 Y10
[gcode_macro HOME_Z]
gcode:
    {% set th = printer.toolhead %}
    {% if "xy" in th.homed_axes %}
        M118 Homing Z-Axis...
        G90
        G0 X185.6 Y110.4 F6000
        G28.1 Z0
        G0 Z5
    {% else %}
        M118 "Must home X and Y first!"
    {% endif %}
[gcode_macro PRINT_END]
description: End print macro
gcode:
    {% set z_safe = 10 %}
    {% set retract_length = 2.0 %}
    # Retract filament slightly
    G91
    G1 E-{retract_length} F1800
    G1 Z{z_safe} F600
    G90
    # Move to park position
    G1 X0 Y0 F6000
    # Turn off part cooling fan
    M107
    # Turn off hotend and bed
    M104 S0                      ; Turn off hotend
    M140 S0                      ; Turn off bed
    M106 S0                      ; Ensure fan is off
    # Disable steppers after delay
    G4 P2000                     ; Wait 2 seconds
    M84                          ; Disable motors
[stepper_x]
step_pin: PF0
dir_pin: PF1
enable_pin: !PD7
microsteps: 16
rotation_distance: 40
endstop_pin: ^PE5
#endstop_pin: ^PE4
position_endstop: 0
position_max: 200
homing_speed: 50
[stepper_y]
step_pin: PF6
dir_pin: PF7
enable_pin: !PF2
microsteps: 16
rotation_distance: 40
endstop_pin: ^PJ1
#endstop_pin: ^PJ0
position_endstop: -15
position_max: 200
position_min: -25
homing_speed: 50
#homing_positive_dir: true
[stepper_z]
step_pin: PL3
dir_pin: PL1
enable_pin: !PK0
microsteps: 16
rotation_distance: 0.7
#endstop_pin: ^PD3
endstop_pin:probe:z_virtual_endstop
#position_endstop: -2.5
position_max: 200
position_min: -10
homing_speed: 10
[extruder]
step_pin: PA4
dir_pin: PA6
enable_pin: !PA2
microsteps:16
rotation_distance: 28.7086  #31.4   #Bondtech 5mm Drive Gears
gear_ratio: 52:10
full_steps_per_rotation: 200    #200 for 1.8 degree, 400 for 0.9 degree
nozzle_diameter: 0.400
filament_diameter: 1.750
min_temp: 0
max_temp: 330
heater_pin: PB4
sensor_type: EPCOS 100K B57560G104F #NTC 100K MGB18-104F39050L32
sensor_pin: PK5
max_power: 1
control :pid
pid_kp : 26.213
pid_ki : 1.304
pid_kd : 131.721
pressure_advance: 0.020
pressure_advance_smooth_time: 0.01
instantaneous_corner_velocity: 2.5
max_extrude_only_distance: 300
max_extrude_only_velocity:60
max_extrude_only_accel:5000
max_extrude_cross_section: 99
min_extrude_temp:100
[heater_bed]
heater_pin: PH5
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PK6
control: watermark
min_temp: 0
max_temp: 130
[fan]
pin: PH6
# Common EXP1 / EXP2 (display) pins
[board_pins]
aliases:
    # Common EXP1 header found on many "all-in-one" ramps clones
    EXP1_1=PC0, EXP1_3=PH0, EXP1_5=PA1, EXP1_7=PA5, EXP1_9=<GND>,
    EXP1_2=PC2, EXP1_4=PH1, EXP1_6=PA3, EXP1_8=PA7, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=PB3, EXP2_3=PC6, EXP2_5=PC4, EXP2_7=PL0, EXP2_9=<GND>,
    EXP2_2=PB1, EXP2_4=PB0, EXP2_6=PB2, EXP2_8=PG0, EXP2_10=<RST>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "spi"
    # Note, some boards wire: EXP2_8=<RST>, EXP2_10=PG0
[probe]
pin: ^PD3
x_offset: -24.25
y_offset: 20.45
#z_offset: 5.0
speed: 10.0
samples: 2
samples_result: median
sample_retract_dist: 3.0
samples_tolerance: 0.05
samples_tolerance_retries: 5
[display]
lcd_type: hd44780
rs_pin: EXP1_4
e_pin: EXP1_3
d4_pin: EXP1_5
d5_pin: EXP1_6
d6_pin: EXP1_7
d7_pin: EXP1_8
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
#kill_pin: ^!EXP2_8
[output_pin beeper]
pin: EXP1_1
[bed_mesh]
mesh_min: 0, 30
mesh_max: 175,150
probe_count: 6, 6
[bed_screws]
screw1: 35, 150
screw2: 150, 150
screw3: 92.5, 150
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [stepper_z]
#*# position_endstop = 1.800
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*#       0.103625, -0.499125, -0.836750, -0.850375, -0.715625, -0.207000
#*#       -0.035000, -0.679875, -0.936375, -0.974375, -0.816250, -0.373750
#*#       -0.032000, -0.638375, -0.883875, -0.887375, -0.741000, -0.363375
#*#       0.153125, -0.297875, -0.729500, -0.707500, -0.548125, -0.233125
#*#       0.299500, -0.010875, -0.248625, -0.253625, -0.172625, -0.060125
#*#       0.348375, 0.176125, 0.042000, -0.000500, 0.046125, 0.075375
#*# x_count = 6
#*# y_count = 6
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*# min_x = 0.0
#*# max_x = 175.0
#*# min_y = 30.0
#*# max_y = 150.0
#*#
#*# [probe]
#*# z_offset = 2.000
#*#
#*# [bed_mesh HOT]
#*# version = 1
#*# points =
#*#       0.103625, -0.499125, -0.836750, -0.850375, -0.715625, -0.207000
#*#       -0.035000, -0.679875, -0.936375, -0.974375, -0.816250, -0.373750
#*#       -0.032000, -0.638375, -0.883875, -0.887375, -0.741000, -0.363375
#*#       0.153125, -0.297875, -0.729500, -0.707500, -0.548125, -0.233125
#*#       0.299500, -0.010875, -0.248625, -0.253625, -0.172625, -0.060125
#*#       0.348375, 0.176125, 0.042000, -0.000500, 0.046125, 0.075375
#*# x_count = 6
#*# y_count = 6
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*# min_x = 0.0
#*# max_x = 175.0
#*# min_y = 30.0
#*# max_y = 150.0
